const sim3d={canvas:null,ctx:null,w:0,h:0,dpr:1,raf:0,key:null,mode:'idle',start:0,pallet:{x:3.0,y:.39,z:2.35,h:1.05},shake:0,impact:0};

function v3(x,y,z){return{x,y,z}}
function sub3(a,b){return v3(a.x-b.x,a.y-b.y,a.z-b.z)}
function dot3(a,b){return a.x*b.x+a.y*b.y+a.z*b.z}
function cross3(a,b){return v3(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x)}
function len3(a){return Math.hypot(a.x,a.y,a.z)||1}
function norm3(a){const l=len3(a);return v3(a.x/l,a.y/l,a.z/l)}
function mix(a,b,t){return a+(b-a)*t}
function ease(t){return t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2}
function cameraBasis(){const pos=v3(5.4,3.9,7.2),target=v3(0,1.15,-.35),up=v3(0,1,0);const f=norm3(sub3(target,pos)),r=norm3(cross3(f,up)),u=cross3(r,f);return{pos,f,r,u}}
function project(p){const c=cameraBasis(),q=sub3(p,c.pos),cx=dot3(q,c.r),cy=dot3(q,c.u),cz=dot3(q,c.f);const fov=sim3d.h*.94,z=Math.max(.35,cz);return{x:sim3d.w/2+cx*fov/z,y:sim3d.h*.54-cy*fov/z,z:cz}}
function shade(hex,f){const n=parseInt(hex.slice(1),16),r=(n>>16)&255,g=(n>>8)&255,b=n&255;return`rgb(${Math.max(0,Math.min(255,r*f))|0},${Math.max(0,Math.min(255,g*f))|0},${Math.max(0,Math.min(255,b*f))|0})`}
function cuboid(x,y,z,w,h,d,color,faces){const x0=x-w/2,x1=x+w/2,y0=y,y1=y+h,z0=z-d/2,z1=z+d/2;const V=[v3(x0,y0,z0),v3(x1,y0,z0),v3(x1,y1,z0),v3(x0,y1,z0),v3(x0,y0,z1),v3(x1,y0,z1),v3(x1,y1,z1),v3(x0,y1,z1)];const ids=[[0,1,2,3],[5,4,7,6],[4,0,3,7],[1,5,6,2],[3,2,6,7],[4,5,1,0]],fs=[.78,.96,.62,.72,1.08,.56];ids.forEach((idx,i)=>{const pts=idx.map(k=>project(V[k]));const zavg=pts.reduce((a,p)=>a+p.z,0)/4;faces.push({pts,z:zavg,color:shade(color,fs[i]),stroke:shade(color,.48)})})}
function drawFloor(ctx){ctx.save();ctx.fillStyle='#9bb4c4';ctx.fillRect(0,0,sim3d.w,sim3d.h);const lines=[];for(let x=-5;x<=5;x+=1){lines.push([v3(x,0,-4),v3(x,0,5)])}for(let z=-4;z<=5;z+=1){lines.push([v3(-5,0,z),v3(5,0,z)])}ctx.strokeStyle='rgba(255,255,255,.25)';ctx.lineWidth=1;lines.forEach(([a,b])=>{const A=project(a),B=project(b);ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke()});ctx.restore()}
function addRack(f){const blue='#164f84',orange='#ef641b';[-1.9,1.9].forEach(x=>[-1.25,1.0].forEach(z=>cuboid(x,0,z,.17,3.25,.17,blue,f)));[0.22,1.58,3.02].forEach(y=>[-1.25,1.0].forEach(z=>cuboid(0,y,z,4.0,.16,.20,orange,f)));[-1.9,1.9].forEach(x=>{cuboid(x,.88,-.12,.14,.13,2.2,blue,f);cuboid(x,2.25,-.12,.14,.13,2.2,blue,f)});[-1.9,1.9].forEach(x=>{for(let i=0;i<6;i++){const t=(i+.5)/6,yy=.35+t*2.45,zz=-1.1+t*2.0;cuboid(x,yy,zz,.12,.12,.55,blue,f)}})}
function addPallet(f,p){const wood='#9a6336',wood2='#bb7e46',box='#c88b50';cuboid(p.x,p.y,p.z,2.7,.16,1.75,wood2,f);[-.95,0,.95].forEach(dx=>[-.55,.55].forEach(dz=>cuboid(p.x+dx,p.y-.18,p.z+dz,.36,.22,.34,wood,f)));cuboid(p.x,p.y+.16,p.z,2.48,p.h,1.58,box,f);const seam='#a86c39';[-.62,0,.62].forEach(dx=>cuboid(p.x+dx,p.y+.18,p.z+0.80,.035,p.h-.04,.025,seam,f));const rows=Math.max(1,Math.round(p.h/.48));for(let i=1;i<rows;i++){const yy=p.y+.16+p.h*(i/rows);cuboid(p.x,yy,p.z+0.80,2.46,.025,.025,seam,f)}}
function render3d(){const c=sim3d.canvas;if(!c)return;const ctx=sim3d.ctx,rect=c.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);if(Math.abs(sim3d.w-rect.width*dpr)>2||Math.abs(sim3d.h-rect.height*dpr)>2){sim3d.dpr=dpr;sim3d.w=Math.max(2,rect.width*dpr);sim3d.h=Math.max(2,rect.height*dpr);c.width=sim3d.w;c.height=sim3d.h;ctx.setTransform(1,0,0,1,0,0);ctx.scale(dpr,dpr);sim3d.w=rect.width;sim3d.h=rect.height}ctx.clearRect(0,0,sim3d.w,sim3d.h);drawFloor(ctx);const faces=[];addRack(faces);if(sim3d.key)addPallet(faces,sim3d.pallet);faces.sort((a,b)=>b.z-a.z);faces.forEach(F=>{ctx.beginPath();F.pts.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=F.color;ctx.fill();ctx.strokeStyle=F.stroke;ctx.lineWidth=1.2;ctx.stroke()});if(sim3d.impact>0){const P=project(v3(0,1.62,1.12)),r=18+sim3d.impact*10;ctx.save();ctx.globalAlpha=.45+.55*sim3d.impact;ctx.strokeStyle='#ff3b30';ctx.lineWidth=6;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(P.x-r,P.y-r);ctx.lineTo(P.x+r,P.y+r);ctx.moveTo(P.x+r,P.y-r);ctx.lineTo(P.x-r,P.y+r);ctx.stroke();ctx.font='900 16px system-ui';ctx.fillStyle='#ff3b30';ctx.textAlign='center';ctx.fillText('BLOCKED',P.x,P.y-r-10);ctx.restore()}sim3d.raf=requestAnimationFrame(render3d)}
function init3d(){if(sim3d.canvas)return;sim3d.canvas=$('rackCanvas');if(!sim3d.canvas)return;sim3d.ctx=sim3d.canvas.getContext('2d');render3d()}
function resetFitTest(){init3d();const fit=$('fitTest');if(fit)fit.classList.remove('fit-success','fit-fail','testing');$('fitResult').textContent='';const help=$('canvasHelp');if(help)help.textContent='Choose a pallet to start the 3D fit test.';sim3d.key=null;sim3d.mode='idle';sim3d.impact=0;sim3d.pallet={x:3.0,y:.56,z:2.35,h:.75}}
function animatePalletFit(key){init3d();const fit=$('fitTest'),result=$('fitResult'),button=$('openPalletPicker'),help=$('canvasHelp');const [name,size]=PALLETS[key];fit.classList.remove('fit-success','fit-fail');fit.classList.add('testing');result.textContent='';sim3d.key=key;sim3d.start=performance.now();sim3d.impact=0;const fits=key==='6000.115.761';const H=fits?.75:key==='6000.115.762'?1.55:2.25;const startX=3.0,startZ=2.35,alignedX=0,baseY=.56;const collisionZ=1.98;const insideZ=.08;sim3d.pallet={x:startX,y:baseY,z:startZ,h:H};if(help)help.textContent=`Testing ${name.replace('📦 ','')} · ${size}`;const duration=fits?3000:2850;function step(now){const t=Math.min(1,(now-sim3d.start)/duration);if(fits){if(t<.34){const q=ease(t/.34);sim3d.pallet.x=mix(startX,alignedX,q);sim3d.pallet.z=startZ;sim3d.pallet.y=baseY}else{const q=ease((t-.34)/.66);sim3d.pallet.x=alignedX;sim3d.pallet.z=mix(startZ,insideZ,q);sim3d.pallet.y=baseY}}else{if(t<.38){const q=ease(t/.38);sim3d.pallet.x=mix(startX,alignedX,q);sim3d.pallet.z=startZ;sim3d.pallet.y=baseY}else if(t<.58){const q=ease((t-.38)/.20);sim3d.pallet.x=alignedX;sim3d.pallet.z=mix(startZ,collisionZ,q);sim3d.pallet.y=baseY}else if(t<.74){const q=(t-.58)/.16;sim3d.impact=1-Math.min(1,Math.abs(q-.5)*1.8);sim3d.pallet.x=Math.sin(q*Math.PI*10)*.055;sim3d.pallet.z=collisionZ+Math.abs(Math.sin(q*Math.PI*8))*.045;sim3d.pallet.y=baseY}else{sim3d.impact=0;const q=ease((t-.74)/.26);sim3d.pallet.x=mix(0,.55,q);sim3d.pallet.z=mix(collisionZ,2.55,q);sim3d.pallet.y=baseY}}if(t<1)requestAnimationFrame(step);else finish()}function finish(){sim3d.impact=0;fit.classList.remove('testing');if(fits){playCorrectSfx();fit.classList.add('fit-success');result.textContent='✓ FITS THE RACK';if(help)help.textContent='Pallet A passes the entrance and is fully inside the rack.';stopTimer();if(button){button.textContent='Pallet Fits';button.disabled=true}setTimeout(()=>overlay('✅','Pallet Fits!','Pallet A fits the rack. ASN creation is complete.',()=>showPage('donePage')),900)}else{playWrongSfx();fit.classList.add('fit-fail');result.textContent='OVER SIZED · BLOCKED AT ENTRANCE';if(help)help.textContent='The load is too tall. It stops at the front beam and bounces back without entering the rack.';message('huMessage',`${name.replace('📦 ','')} is over sized. It is blocked at the rack entrance because its height exceeds 500 mm.`);state.palletAnimationLocked=false;if(button){button.disabled=false;button.classList.remove('testing-button');button.textContent='Choose Another Pallet'}}}requestAnimationFrame(step)}
